### PR TITLE
Implement #1

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**

### CODE REVIEW

**Comment by J-D-K** [comment]
I was actually going to just copy and paste the copyDirToDir function over from JKSV for this. It would grab them all at one shot instead of needing to be cycled through.

**Comment by ThatNerdyPikachu** [comment]
That works too. Should I close?

**Comment by J-D-K** [comment]
Not yet. I'm having problems with it instantly crashing. If it starts taking too long, I'll merge yours instead.

**Comment by ThatNerdyPikachu** [comment]
Sounds good.

**Comment by J-D-K** [comment]
Closing this one. I got it taken care of.

**Pull request closed without merging**
